services:
  # --- Kafka (KRaft mode, no Zookeeper needed) ---
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"       # host access (from your laptop / IDE)
      - "29092:29092"     # internal access (from other containers, e.g. Flink)
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: "SaaGKvp1TbSoXeISClKjpQ"
    volumes:
      - kafka-data:/var/lib/kafka/data

  # --- Kafka UI (optional but very useful for debugging topics visually) ---
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: urbanpulse
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka

  # --- Flink JobManager ---
  jobmanager:
    image: flink:1.20-java17
    container_name: flink-jobmanager
    ports:
      - "8081:8081"        # Flink Web UI
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./target:/opt/flink/usrlib   # drop your built jar here to submit

  # --- Flink TaskManager ---
  taskmanager:
    image: flink:1.20-java17
    container_name: flink-taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
    volumes:
      - ./target:/opt/flink/usrlib

  # --- Spark Master ---
  spark-master:
    image: spark:3.5.3
    container_name: spark-master
    ports:
      - "8083:8080"        # Spark Web UI
      - "7077:7077"        # Spark master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_MASTER_HOST=spark-master
    volumes:
      - ./spark_jobs:/opt/spark/jobs
      - ./data:/opt/spark/data

  # --- Spark Worker ---
  spark-worker:
    image: spark:3.5.3
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8084:8080"        # Spark worker Web UI
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=2g
    volumes:
      - ./spark_jobs:/opt/spark/jobs
      - ./data:/opt/spark/data

volumes:
  kafka-data:
